language: csharp
sudo: false
env:
  global:
    - CONFIGURATION="Release"
mono:
  - 3.12.0
  - 3.10.0
solution: Persimmon.sln

script:
  - xbuild ./Persimmon.sln /p:Configuration=${CONFIGURATION}
  - mono --runtime=v4.0 ./Persimmon.Console/bin/${CONFIGURATION}/Persimmon.Console.exe ./Persimmon.Tests/bin/${CONFIGURATION}/Persimmon.Tests.dll ./Persimmon.Script.Tests/bin/${CONFIGURATION}/Persimmon.Script.Tests.dll

