language: objective-c

env:
  matrix:
    - MONO_VERSION="3.10.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - mono --runtime=v4.0 ./.nuget/NuGet.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory packages -ExcludeVersion

script:
  - xbuild ./Persimmon.sln /p:Configuration=Release
  - mono --runtime=v4.0 ./packages/NUnit.Runners/tools/nunit-console.exe ./Persimmon.Tests/bin/Release/Persimmon.Tests.dll

