language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.1
    - os: osx
      osx_image: xcode8.1
      mono: latest
      dotnet: 1.0.1

before_script:
  - chmod +x ./build.sh
script:
  - dotnet --info
  - ./build.sh
