branches:
  except:
    - gh-pages

configuration:
  - Release

test_script:
  - Start-Process -FilePath "Persimmon.Console\bin\$env:configuration\Persimmon.Console.exe" -ArgumentList "Persimmon.Tests\bin\$env:configuration\Persimmon.Tests.dll"
