version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

configuration:
  - Release

test_script:
  - ps: iex "Persimmon.Console\bin\$env:configuration\Persimmon.Console.exe Persimmon.Tests\bin\$env:configuration\Persimmon.Tests.dll Persimmon.Script.Tests\bin\$env:configuration\Persimmon.Script.Tests.dll"
